Jeff-Duke/turing-fridays

lib/components/App.js, lib/index.js, package.json, public/index.html, public/main.bundle.js, webpack.config.js
initial router is setup. Need to come back to issue regarding our / directory not being set up correctly.
=> initial router setup

lib/components/App.js, lib/components/Header.js, lib/components/SignIn.js, lib/components/Spike.js, lib/components/Spikes.js, lib/firebase.js, package.json
first pass at creating/rendering spikes
=> Initial component setup

lib/allAdmins.js, lib/components/Admin.js, lib/components/AdminSpike.js, lib/components/App.js, lib/components/Header.js, lib/components/Spike.js, lib/components/Spikes.js, lib/styles/_header.scss, lib/styles/_spike.scss, lib/styles/main.scss
Admin can approve spikes, which are not rendered to non-admins if they have not been approved.
Admin can assign a room to a given spike.
=> Admin views added

lib/allAdmins.js, lib/components/App.js, lib/components/Header.js, lib/components/Spike.js, lib/components/Spikes.js, lib/styles/_proposalForm.scss, lib/styles/main.scss
input fields are cleared on submit. Might be a better implementation but this one gets the job done for now without overcomplicating it.
=> form is cleared on submit

lib/allAdmins.js, lib/components/Admin.js, lib/components/AdminSpike.js, lib/components/App.js, lib/components/Header.js, lib/components/SignIn.js, lib/components/Spike.js, lib/components/Spikes.js, lib/index.js, package.json, test/App.spec.js, webpack.config.js
This PR installs the dev dependency for jsdom since we were requiring it in test -> helpers -> setup.js but it wasn't listed in our package.json.  This PR also consolidates JS formatting to be consistent across components.
Tried to run test suite.  Received error that jsdom wasn't loaded.  Installed jsdom.
=> Test and format

lib/allAdmins.js, lib/components/Admin.js, lib/components/App.js, lib/components/Header.js, package.json, test/App.spec.js, test/helpers/mockUsers.js
This PR adds a testing suite for the App component.  The tests check if component is rendering as expected if there is no user logged in, as well as if there is a user logged in.  It also tests for default state.
I created a mock users file in test/helpers so we could mock a user state on the App component, otherwise we couldn't get past the initial sign in page.  
I am still attempting to get admin login rendering correctly.  It is not recognizing the Admin component.  For some reason the test will work if I remove the bang from App line 79 "if(!allAdmins.indexOf(user.email)) "  but then the regular user Spikes test fails.  Will need to test this out further to figure out what the issue is.
=> App component testing successful.

lib/allAdmins.js, lib/components/App.js, lib/styles/partials/_spike.scss, public/index.html, test/App.spec.js, test/helpers/mockUsers.js
admin testing now working, minor styling improvements for breaking long words in spikes
To get the admin testing working I updated the data structure of the dummy userData so it correctly evaluated a user as an admin.
=> Minor updates closes #19

lib/allAdmins.js, lib/components/Admin.js, lib/components/App.js, lib/components/Spike.js, lib/components/Spikes.js, lib/styles/partials/_spike.scss
We were having scoping issues with our methods based on how we were passing them down.  This PR fixes that, now when we call a method from a child component and it bubbles up to the App component, we still have scope for the app component and access to state.  I have refactored both the user and admin functions to pass information properly.
Paired with Steve who pointed out the issue of how we were calling the functions.  Went through our code and updated/refactored as needed.
Verified functionality is working and verified passing test suite.  This PR is ready to merge pending code review.
=> refactor our functions in the app component to fix scope issues

lib/components/Admin.js, lib/components/App.js
=> Admins can now add and delete other admins

lib/components/Spike.js, lib/styles/partials/_proposal-form.scss
Add form modal on the toggle "Add Spike" button
Fix the bug with adding spikes - calling two functions within an input field was breaking the adding spike functionality
=> add pop up modal form

lib/components/AdminSpike.js, lib/components/App.js
the else clause at this point is only console logging that your submission didn't work, we will need to build a ui component which lets the user know that their spike was not submitted and why
=> cannot submit a spike without a description and a title

lib/components/Admin.js, lib/components/App.js, lib/components/Spike.js, lib/components/Spikes.js
The default is to show the current week, with Spikes from the last 24 hours being showed so on Friday we can still see the spikes.  
If a user selects another date, it shows the same range from that date.
We can get more specific with this so if a user selects a date it will explicitly show that date, but I would look to you all for feedback on whether we want to do that or not.
=> User filters are now in place

lib/components/Admin.js, lib/components/AdminList.js, lib/styles/partials/_admin-spike.scss, lib/styles/partials/_admins.scss, lib/styles/partials/_body.scss
Created an animated sidebar for the admin list. Functionality of submitting a new admin email works just as before. For some reason the "transition" on the `AdminList` element only occurs once after the first click. Not sure why this is happening, but I added a "transition" on the body and it makes the animation smoother. Also cleaned up the Admin component by making the quotes consistent with single quotes. When we do a final refactor we should definitely keep an eye out for this inconsistency and fix it. 
No conflicts, this branch is able to merge. 
closes #34
=> Style admin list

lib/components/Admin.js, lib/components/AdminList.js, lib/components/App.js, lib/styles/partials/_admins.scss, lib/styles/partials/_body.scss
This fixes a bug with the adminList component.  Kirsten pointed out it did not have the newAdmin function it needed, which was causing an error if you tried to submit.  Now, that function is passed down and I receive a permission denied from firebase.
=> Fix new admin

lib/components/AdminSpike.js, lib/components/Spike.js
on the admin page, a user sees a dropdown to select the location of choice.
=> basic dropdown to pick location closes #66

lib/components/Admin.js, lib/components/Header.js, lib/components/Spikes.js, lib/styles/partials/_admins.scss, lib/styles/partials/_proposal-form.scss, package.json
Attempted testing, but unable to mock a user even with the mock data...so I worked on implementing animation back into the admin list and modal 
Add some nice UI features with animation. Since we can't use the typical CSS animations on React components with state we needed an animation library specific for React [Animation Add-ons](https://facebook.github.io/react/docs/animation.html) Animated the admin list and the form modal.
=> animate containers

lib/components/AdminSpike.js, lib/components/App.js, lib/components/Spike.js
=> admin can now toggle approved status

lib/components/Admin.js, lib/components/GuestSpeaker.js, lib/components/GuestSpeakerForm.js, lib/styles/main.scss, lib/styles/modules/_mixins.scss, lib/styles/modules/_variables.scss, lib/styles/partials/_admin-spike.scss, lib/styles/partials/_admins.scss, lib/styles/partials/_body.scss, lib/styles/partials/_floor-map.scss, lib/styles/partials/_guest-speaker.scss, lib/styles/partials/_proposal-form.scss, lib/styles/partials/_spike.scss
Restyle admin spike cards to be more similar to the user spike cards
Make the speaker form a modal and hide and show it on click 
Style guest speaker form on the admin side 
Decide if we keep the attendees email list and if so it needs to be styled
Style the guest speaker info on the user side
THIS PR IS READY TO MERGE
closes #88
=> Change admin color scheme

lib/components/Admin.js, lib/components/App.js, lib/components/Spikes.js
This pr includes the floor map modal into the user side of the application.  It also adds basic styling for the dropdown to select a filter.
I refactored the assignClassrooms function from the Admin to the App so we could use it on both the Admin component and the Spikes component.
=> Map available for User as well, User filter by date styled

lib/components/Admin.js, lib/components/GuestSpeaker.js, lib/components/GuestSpeakerForm.js, lib/components/Spikes.js, lib/styles/partials/_body.scss, lib/styles/partials/_guest-speaker.scss, lib/styles/partials/_header.scss, lib/styles/partials/_spike.scss
Both Admin and User page shows guest speaker.  User view of spike cards now has same style and spacing as admin spike cards.
=> Styled Guest Speaker component and reformat style of Spike component - Closes #60 and Closes #90

lib/components/AdminSpike.js, lib/components/App.js
=> Remove prior dates

lib/components/Admin.js, lib/components/AdminList.js, lib/components/AdminSpike.js, lib/components/GearUpForm.js, lib/components/GuestSpeakerForm.js, lib/components/Header.js, lib/components/Spike.js, lib/components/Spikes.js, lib/styles/modules/_mixins.scss, lib/styles/partials/_admin-spike.scss, lib/styles/partials/_admins.scss, lib/styles/partials/_floor-map.scss, lib/styles/partials/_guest-speaker.scss, lib/styles/partials/_header.scss, lib/styles/partials/_proposal-form.scss, lib/styles/partials/_sign-in.scss, lib/styles/partials/_spike.scss
All accessibility tests through the aXe Chrome extension pass on both the admin and user pages 
Needed to add `label` tags to form elements, add `src` attributes to images, and fix color contrasts
(the teal and white combo on Turing's website didn't pass the color contrast test, so I used the same color to stick with their color theme, but darkened it until it passed with enough contrast)
Hopefully you can see things better! @kerrd89 
closes #73
=> all axe accessibility tests pass

lib/components/Admin.js, lib/components/App.js, lib/components/GearUpForm.js, lib/components/GuestSpeakerForm.js
this pr passes down the sanitize input to the gearup and speakerform, clears some bugs created by styling, and passes a toggle state down into each to hide the form after it is submitted.
=> sanitizes inputs for gearup an speaker and fixed form submit closes #107

lib/components/Admin.js, lib/components/AdminSpike.js, lib/components/App.js, lib/components/GearUpForm.js, lib/components/GuestSpeakerForm.js, lib/components/Spikes.js, test/Admin.spec.js, test/AdminSpike.spec.js, test/App.spec.js, test/Spike.spec.js, test/Spikes.spec.js
Had fourteen failing tests from code updates and merges from the past couple of days.  I had to move the assignRooms function out of App as the entire test suite would not run the way it was (similar to the dateOptions problem we had previously).  The suite kept saying it was not a function.
=> Fix failing tests

lib/components/Spike.js
This PR marks the fields in the spike form that are required
=> mark required fields for users

lib/styles/partials/_admins.scss, lib/styles/partials/_buttons-dropdowns.scss, lib/styles/partials/_guest-speaker-and-gearup.scss
=> fix media query

lib/components/Admin.js, lib/components/App.js, lib/components/GuestSpeaker.js, lib/styles/partials/_buttons-dropdowns.scss
This PR adds RSVP functionality to the guest speaker.  A user will see a 'Join' / 'Leave' button.  Clicking the button adds their email address to the attendees list which increments the count shown on the page.  **Admins will not see the join/leave button, only the count**
Added a function that checks to see if there are attendees assigned to a guest-speaker, checks to see if you're attending and then adds or removes you from the list accordingly.  The button text is conditionally rendered based on if your email is in the attendees list.
None, PR is ready to merge pending code review.
=> Speaker rsvp -- Closes #123

lib/components/AdminSpike.js, lib/components/EditableSvg.js
Added and editable-svg component which returns the pencil.  The pencil is visible on the admin page for only the title, description, and hosts fields.
=> editable-svg in place

lib/components/AdminSpike.js, lib/styles/partials/_admin-spike.scss, lib/styles/partials/_buttons-dropdowns.scss, lib/styles/partials/_floor-map.scss
Add a checkmark svg to show admin the spike has been approved
On default the caution svg will be rendered when the spike card is first created
=> add spike status icons and toggle when spike is approved

lib/components/Admin.js, lib/components/FloorMap.js, lib/components/Spikes.js
This PR adds the count of attendees to the map for both the users and the admins.  
Updated the assign-rooms functions to assign an object to each room that has the spike title and the attendees count or 0 if no attendees.  
None this PR is ready to merge pending code review.
=> Map attendees -- Closes #126

README.md, lib/styles/partials/_admin-spike.scss, lib/styles/partials/_guest-speaker-and-gearup.scss
Added padding to Guest Speaker and Gear Up announcements 
Added gif back to the README.md
=> Adjust padding and add gif to README.md

package.json
This PR adds a deployment script to the package.json which runs build then deploys to firebase
=> add deployment scipt
