lib/index.js
lib/styles/_body.scss
lib/styles/main.scss
package.json

We needed to install the "style-loader" and "resolve-url-loader" npm packages in order to get our styling wired up correctly. The "resolve-url-loader" will come in handy when we have images since it directs the images relative to the .scss file.
[resolve-url-loader npm package](https://www.npmjs.com/package/resolve-url-loader)
After these were installed we could require the "main.scss" file in the "index.js" file. Now when you fire up the server the background should be a light green.

require sass in index.js and add npm packages

---

lib/allAdmins.js
lib/components/Admin.js
lib/components/App.js
lib/components/Spike.js
lib/components/Spikes.js

This PR gets rid of the global firebase.user variable and instead passes the currently logged in user down to the create-spike component so that when a user or admin creates a new spike, their user info is available to that object.
Worked through the code with Pete and looked for ways to refactor.

refactor out global variable, pass user to components like a good person

---

lib/components/Admin.js
lib/components/AdminSpike.js
lib/components/App.js
lib/components/Header.js
lib/components/Spike.js
lib/components/Spikes.js

This PR updates our vote counting setup so that a user can only rsvp once to a spike session.  We now have an attendees list and we're displaying the count of how many unique attendees there are.  
We created an attendees key on the spike when it's created, the creator is added as the first attendee by default.  When a user logs in and clicks on the vote button they're added to the attendees list.
none - this can be merged pending code review

One user one vote per spike

---

lib/allAdmins.js
lib/components/AdminSpike.js
lib/components/App.js
lib/components/Spike.js
package.json

This PR adds an attendees list to the admin view.  This allows an admin to see a full list of who will attend a spike, not just a count.  This PR also fixes a bug from the previous PR whereby the app would throw errors if the attendees count reached 0.
The admin page now has a UL that checks to see if there is an attendees list for a spike, if so it renders list-items for each attendee.  
The bug with the empty attendee list is due to Firebase not allowing an empty array as a value on an object.  Had to add a check to see if there is an attendees key on the spike, if not it creates one and adds the user's email.  
None - this PR is ready to merge pending code review.

Attendees list

---

lib/components/AdminSpike.js
package.json

this solves the bug of multiple attendees not rendering.  the issue was a uuid package which we had all not npm installed.  we bypass this issue by using the index of the attendees as a primary key and remove the uuid dependency.

multiple attendees now rendering again

---

lib/allAdmins.js
lib/components/Admin.js
lib/components/AdminSpike.js
lib/components/Spike.js
lib/components/Spikes.js
lib/styles/main.scss
lib/styles/modules/_mixins.scss
lib/styles/partials/_admin-spike.scss
lib/styles/partials/_header.scss
lib/styles/partials/_proposal-form.scss
lib/styles/partials/_sign-in.scss
lib/styles/partials/_spike.scss

Ignore the comment about ignoring the PR.  That was something I was trying to do yesterday and didn't want anyone to think it was something ready for production.  I cannot seem to delete that commit.  This still needs review and approval.
Purpose:  We needed to enable the user to be able to check radio buttons for more than one  spike card on the admin page.  Also needed to disable the approve button if spike had already been approved.  We needed descriptors on all of the spike details as there were none to explain what each field was.  Throughout the process of this I also incorporated a similar styling format as the user page.  Because of this, I made some adjustments to the mixins and the buttons across all components so that button styling was consistent across the app. 
Execution: …

Update admin functionality and styling of admin page. Closes #24 and #20

---

lib/components/AdminSpike.js
lib/components/App.js
lib/components/Spike.js
lib/styles/partials/_proposal-form.scss

This PR adds a new date field to the spike creation form that lets the creator pick which date they'd like the spike scheduled for.  This will allow a creator to schedule a spike for weeks into the future.
PR also fixes a couple bugs where the buttons/forms were reloading the page on click and this was appending information to the url.  by using `e.preventDefault()` this prevents the default submit and fixes the bug of the URL changing.
Added a new date field to the spike form with a type of date.  Added a new key-value pair to the spike object before it goes to the database.  

add a date field to schedule the spike - Closes #36, Closes #38, Closes #50

---

lib/components/Spike.js
lib/styles/partials/_spike.scss

This PR fixes a UI issue where words were breaking inside the spike card and admin spike card containers.
I changed the overflow-wrap and word-wrap CSS properties to "normal" instead of "break-word".  I also removed the word-break property as it was not needed.

Fixed word wrap issue so words don't break in the middle - Closes #39

---

lib/components/AdminSpike.js
lib/components/App.js
lib/components/Spike.js
lib/styles/partials/_proposal-form.scss

This PR adds the ability for user to identify which students and/or posses are hosting the spike session.  It also enables the user to add notes for the staff about any extra needs they may have for the session.  Spike hosts is now displayed on both UI and Admin interface.  Notes for staff is only rendered on Admin page.
The implementation was pretty straightforward as described in the purpose. I also moved the "approval status" into the location container as it made more sense that all of the admin-related activities were in one section.  I also updated the styling of the spike form to reflect the added fields.

Added input and display fields for spike hosts and notes for staff - Closes #27

---

lib/components/App.js

This PR changes functionality so that a user can only RSVP to one session at a time.  I've added an 'attending' field to our state.  When App is mounted, the spikes are mapped through and if the user is set to attend a session that session is put in state.  Any time a user joins a state the function checks to see if they're already attending a spike, if so the user is removed from that spike before they are added to the new spike.  If a user leaves a spike they've joined, attending is set to null.  
I broke out our functions a bit.  I've added a `joinSpike` and `leaveSpike` method, a `setAttending` method for when the app is first loaded and an `updateAttending` method that's called when a user joins or leaves a session.  This sets us up for some cool UI features.  We could render a …

Limit to attending 1 session at a time -- Closes # 47

---

lib/components/App.js

The spacing looks off here on github, but input sanitization appears to be working.
My approach:
I found a blog on the subject and sent the reg-ex function from that to alex to ask for his opinion.  He suggested we look into sanitize-html, but provided a functional alternative as well.
I tried a npm module called 'sanitize-html', but there were peer dependencies which were causing issues. 
The function I found on the aforementioned blog worked for rendering traditional html, but doesn't work for react (replacing symbols with their text equivalent).
Long story short, I am using the function alex provided and it appears to do the job.  We still need to validate email though seperately on both the newAdmin side and the newSpike side.

Sanitize input closes #68

---

lib/components/App.js

This spike solves the issue of the earliest date available showing, rather than the nearest spike.  Old spikes are being excluded when we set the firebase data to state, spikes older than one year are being deleted at the same time.

Only current spikes being imported, spikes older than 1 year are deleted

---

lib/components/Admin.js
lib/components/AdminSpike.js
lib/components/App.js
lib/components/Spikes.js

This PR updates the UI for the user so that they are able to see a spike if it has not yet been approved.  The user sees a modified version of the admin card so they can see the attendees list and are able to delete the spike they've created.

Update UI to show your pending spikes -- Closes #69, Closes #97

---

lib/components/Admin.js
lib/components/AdminSpike.js
lib/components/GearUpForm.js
lib/components/GuestSpeakerForm.js
lib/styles/main.scss
lib/styles/modules/_mixins.scss
lib/styles/partials/_admin-spike.scss
lib/styles/partials/_admins.scss
lib/styles/partials/_guest-speaker.scss
lib/styles/partials/_header.scss
lib/styles/partials/_modals.scss
lib/styles/partials/_proposal-form.scss
lib/styles/partials/_spike.scss

Admin page is now fully responsive, checked on ipads and all mobile devices 
Made gear up form a modal 
Styled attendee email list - Wasn't able to animate it because the `<ReactCSSTransitionGroup>` needs to wrap the state of the component, but since this admin card is stateless we can't do that. Perhaps someone can look into how this can be changed, but for right now it's styled, but doesn't have sliding animation.
Added `overflow-y: scroll` to the modal, so hopefully the modal can scroll on mobile when the phone is sideways, can only test if the app is deployed with the latest changes
closes #95
closes #106 
closes #105

Responsive admin page and style gear up form 

---

lib/components/AdminSpike.js
lib/components/App.js

This PR gives admins, or users viewing their own spike (before it has been approved) the ability to edit the title, description and hosts fields.  onBlur they are updated in the DB.
Had to make the admin-spike a class-component and create a method that takes the prop, spike and new value and calls our updateSpike function.  
None - this is ready to merge pending code review

make title, description and hosts editable -- Closes #71

---

lib/components/AdminSpike.js
lib/components/App.js

This PR fixes the issue where our dates were off by a day.  This had to do with the UTC offset.  
Our date was coming from the HTML 5 element as YYYY-MM-DD and when creating a new Date from that it was creating a date in UTC tz.  I used Moment to reformat the date into MM-DD-YYYY and the Date object creates this with UTC offset in mind.
None - this code is ready to merge pending code review

Format dates

---

lib/components/Admin.js
lib/components/App.js
lib/components/Spike.js
lib/components/Spikes.js

This PR fixes the issue where spikes are not rendered to the page the first time a user visits.  Now when a user or admin log into the page for the very first time, and each subsequent visit, all spikes and info are rendered to the page. 
Abstracted our firebase calls out into their own functions.  Fetching the admins, spikes, gearup and speaker does not happen until a user is received back from firebase.  Updated the spikes and admin components to track the spikes rec'd in their own state.  Abstracted our function that updates the date filter and spikes and call it on `componentDidMount` and `componentWillReceiveProps`  Updated functions and render methods accordingly.

Render spikes on the first load of the page - Closes #137

---

lib/components/GuestSpeaker.js
lib/styles/partials/_buttons-dropdowns.scss
lib/styles/partials/_guest-speaker-and-gearup.scss

This PR adjusts the background and font colors of the guest speaker info link and the gear up markdown link for a better UX.
I styled these elements in the same manner as regular buttons on the page for consistency.  I first attempted to merely change the font color to our teal accent, but the link still was not differentiated enough from the rest of the text, thus I added background and button styling to make links more distinct.  I also adjusted some padding and margins of those elements and some of their neighboring elements for all screen sizes.  In addition, to maintain visual consistency between the gear up and guest speaker components I moved the link to guest speaker to the bottom of the containing div.

Tweak styling for links to guest speaker info and gearup markdown - Closes #146

---

database.rules.json

this PR removes a trailing comma in the db rules that was causing issues with deploying to firebase.

remove trailing comma in firebase rules

---

database.rules.json
lib/components/Admin.js
lib/components/AdminList.js

This PR changes the super-admin (control over adding/removing other admins) from Pete over to Ilana.  
Removed Pete's email from codebase and put in my own, tested as working then changed mine over to Ilana. 
This is not a very good way to be handling authentication for this role.  We should add another role in Firebase for a super-admin and then render our conditionals, and configure our database write rules for this. 
For now, it should get Ilana to a point where she can add and remove admins as needed.

remove pete and make ilana super admin
